chore(datepickers): position clear button
einride/ui pull request #895
Opened 2023-01-12 09:12 UTC by LucidityDesign

2023-01-12 11:33 UTC, filiptammergard requested changes

2023-01-12 11:33 UTC, filiptammergard commented on src/components/controls/dates/DateRangePicker/DateRangePicker.tsx
> +    inline-size: ${({ theme }) => 4 * theme.spacingBase}rem;
```suggestion
    inline-size: ${({ theme }) => 3 * theme.spacingBase}rem;
```

2023-01-12 11:33 UTC, filiptammergard commented on src/components/controls/dates/DatePicker/DatePicker.tsx
> +      ${({ theme, clearable }) => (clearable ? 6 : 2) * theme.spacingBase}rem;
Let's add `clearable` to the `StyledDatePickerProps` to avoid relying on Mantine's `clearable` prop implicitly. What do you think?

2023-01-12 11:33 UTC, filiptammergard commented on src/components/controls/dates/DatePicker/DatePicker.tsx
> +    inline-size: ${({ theme }) => 4 * theme.spacingBase}rem;
By making this 24px, we can make it look exactly like the other components with a right icon:

![image](https://user-images.githubusercontent.com/44197016/212055555-190d229a-0050-483f-a903-49606941f2ad.png)


```suggestion
    inline-size: ${({ theme }) => 3 * theme.spacingBase}rem;
```

2023-01-12 12:11 UTC, LucidityDesign commented on src/components/controls/dates/DatePicker/DatePicker.tsx
> +    inline-size: ${({ theme }) => 4 * theme.spacingBase}rem;
Good point!

2023-01-16 07:41 UTC, filiptammergard approved these changes
Looks like comments are resolved! I don't get notified on resolved comments, so feel free to request review/comment in my comment when things are resolved.

This looks good! Let's squash commits into one `fix` commit!

2023-01-16 08:47 UTC, merged