chore(Sheets): prevent content underneath actions
einride/ui pull request #896
Opened 2023-01-12 09:42 UTC by LucidityDesign

2023-01-12 09:45 UTC, LucidityDesign commented on src/components/views/Sheets/Sheets.tsx
> +    display: block;
This is not needed. However I tried to keep the original display of the component

2023-01-12 11:04 UTC, filiptammergard requested changes
In this case, the commit message should be a `fix`, to make sure a patch version is released when merging. The other two suggestions are optional. Looks good!

2023-01-12 11:04 UTC, filiptammergard commented on src/components/views/Sheets/Sheets.tsx
> +  margin-block: ${({ theme }) => theme.spacingBase}rem ${({ theme }) => 2 * theme.spacingBase}rem;
I would do it like this here which I think is a bit easier to read, but you can choose!

```suggestion
  margin-block-start: ${({ theme }) => theme.spacingBase}rem;
  margin-block-end: ${({ theme }) => 2 * theme.spacingBase}rem;
```

2023-01-16 07:45 UTC, filiptammergard approved these changes
Nice!

2023-01-16 08:53 UTC, merged